"""scenario team snapshot subgroup

Revision ID: c94098dd7ead
Revises: 9c30cca1e353
Create Date: 2026-08-31 16:29:07.445344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94098dd7ead'
down_revision: Union[str, None] = '9c30cca1e353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_team_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subgroup_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_team_snapshots', schema=None) as batch_op:
        batch_op.drop_column('subgroup_name')

    # ### end Alembic commands ###
